-- 05_seed_tipo_detencion.sql — GENERADO por scripts/generar_seed_tipo_detencion.py; no editar a mano.
-- Origen: hoja PCS-Fault de AvailabilityCalculation_PCS&Batteries_20260907_septiembre 2026.xlsm
-- 163 códigos distintos. Duplicados resueltos (F-35, D-14):
--   F228: 2 filas; se usa Significado='Crítico' (descartado 'Parcial') — D-14
--   F230: 2 filas; se usa Significado='Crítico' (descartado 'Parcial') — D-14
--   F231: 2 filas; se usa Significado='Crítico' (descartado 'Parcial') — D-14
--   F232: 2 filas; se usa Significado='Crítico' (descartado 'Parcial') — D-14
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

MERGE dbo.tipo_detencion AS t
USING (VALUES
    (0, N'F0', N'NO FAULT', N'F0 NO FAULT', N'No fault', N'Yes'),
    (1, N'F1', N'Watchdog', N'F1 Watchdog', N'Crítico', N'No'),
    (2, N'F2', N'HW Vbus', N'F2 HW Vbus', N'Crítico', N'No'),
    (3, N'F3', N'Carga suave', N'F3 Carga suave', N'Crítico', N'No'),
    (4, N'F4', N'Descarga', N'F4 Descarga', N'Crítico', N'No'),
    (5, N'F5', N'Alta VAC', N'F5 Alta VAC', N'Crítico', N'No'),
    (6, N'F6', N'Baja VAC', N'F6 Baja VAC', N'Crítico', N'No'),
    (7, N'F7', N'Alta frecuencia', N'F7 Alta frecuencia', N'Crítico', N'No'),
    (8, N'F8', N'Baja frecuencia', N'F8 Baja frecuencia', N'Crítico', N'No'),
    (10, N'F10', N'Coms CIF FPGA-DSP', N'F10 Coms CIF FPGA-DSP', N'Crítico', N'No'),
    (11, N'F11', N'Anti-isla activo', N'F11 Anti-isla activo', N'Crítico', N'No'),
    (13, N'F13', N'No módulos', N'F13 No módulos', N'Crítico', N'No'),
    (14, N'F14', N'Drive-Select DSP', N'F14 Drive-Select DSP', N'Crítico', N'No'),
    (15, N'F15', N'Sincronización', N'F15 Sincronización', N'Crítico', N'No'),
    (23, N'F23', N'VAC desbalanceada', N'F23 VAC desbalanceada', N'Crítico', N'No'),
    (25, N'F25', N'Baja VDC', N'F25 Baja VDC', N'Crítico', N'No'),
    (27, N'F27', N'Fallo arranque módulos', N'F27 Fallo arranque módulos', N'Crítico', N'No'),
    (28, N'F28', N'Anti-isla pasivo', N'F28 Anti-isla pasivo', N'Crítico', N'No'),
    (31, N'F31', N'Fallo autodiagnóstico', N'F31 Fallo autodiagnóstico', N'Crítico', N'No'),
    (32, N'F32', N'Error módulo autodiagnóstico', N'F32 Error módulo autodiagnóstico', N'Crítico', N'No'),
    (33, N'F33', N'Incapaz reconectar', N'F33 Incapaz reconectar', N'Crítico', N'No'),
    (35, N'F35', N'Premag MT', N'F35 Premag MT', N'Crítico', N'No'),
    (40, N'F40', N'Sobretemperatura interna', N'F40 Sobretemperatura interna', N'Crítico', N'No'),
    (41, N'F41', N'GFDI', N'F41 GFDI', N'Crítico', N'No'),
    (43, N'F43', N'Paro emergencia', N'F43 Paro emergencia', N'Crítico', N'No'),
    (44, N'F44', N'Drive-Select MCU', N'F44 Drive-Select MCU', N'Crítico', N'No'),
    (45, N'F45', N'Aislamiento general', N'F45 Aislamiento general', N'Crítico', N'No'),
    (46, N'F46', N'Fallo de datos', N'F46 Fallo de datos', N'Crítico', N'No'),
    (47, N'F47', N'Watchdog uP', N'F47 Watchdog uP', N'Crítico', N'No'),
    (48, N'F48', N'Comunicaciones internas', N'F48 Comunicaciones internas', N'Crítico', N'No'),
    (49, N'F49', N'IMD autodiagnóstico error', N'F49 IMD autodiagnóstico error', N'Crítico', N'No'),
    (51, N'F51', N'Comunicaciones PPC', N'F51 Comunicaciones PPC', N'Comunicación', N'No'),
    (54, N'F54', N'Sobrecorriente', N'F54 Sobrecorriente', N'Crítico', N'No'),
    (55, N'F55', N'Fallo externo', N'F55 Fallo externo', N'Crítico', N'No'),
    (56, N'F56', N'Paro emergencia remoto', N'F56 Paro emergencia remoto', N'Crítico', N'No'),
    (58, N'F58', N'SW control incompatible', N'F58 SW control incompatible', N'Crítico', N'No'),
    (59, N'F59', N'SW módulo incompatible', N'F59 SW módulo incompatible', N'Crítico', N'No'),
    (62, N'F62', N'Comunicaciones DU', N'F62 Comunicaciones DU', N'Crítico', N'No'),
    (63, N'F63', N'IMD conexión tierra', N'F63 IMD conexión tierra', N'Crítico', N'No'),
    (64, N'F64', N'MAC inválida', N'F64 MAC inválida', N'Comunicación', N'No'),
    (65, N'F65', N'Sobreintensidad AC', N'F65 Sobreintensidad AC', N'Crítico', N'No'),
    (66, N'F66', N'Desbalanceo VDC módulo', N'F66 Desbalanceo VDC módulo', N'Crítico', N'No'),
    (69, N'F69', N'Sobretensión DC+', N'F69 Sobretensión DC+', N'Crítico', N'No'),
    (70, N'F70', N'Sobretensión DC-', N'F70 Sobretensión DC-', N'Crítico', N'No'),
    (71, N'F71', N'Desaturación R1(H)', N'F71 Desaturación R1(H)', N'Crítico', N'No'),
    (72, N'F72', N'Desaturación R2(H)', N'F72 Desaturación R2(H)', N'Crítico', N'No'),
    (73, N'F73', N'Desaturación R2(L)', N'F73 Desaturación R2(L)', N'Crítico', N'No'),
    (74, N'F74', N'Desaturación R3(L)', N'F74 Desaturación R3(L)', N'Crítico', N'No'),
    (75, N'F75', N'Desaturación S1(H)', N'F75 Desaturación S1(H)', N'Crítico', N'No'),
    (76, N'F76', N'Desaturación S2(H)', N'F76 Desaturación S2(H)', N'Crítico', N'No'),
    (77, N'F77', N'Desaturación S2(L)', N'F77 Desaturación S2(L)', N'Crítico', N'No'),
    (78, N'F78', N'Desaturación S3(L)', N'F78 Desaturación S3(L)', N'Crítico', N'No'),
    (79, N'F79', N'Desaturación T1(H)', N'F79 Desaturación T1(H)', N'Crítico', N'No'),
    (80, N'F80', N'Desaturación T2(H)', N'F80 Desaturación T2(H)', N'Crítico', N'No'),
    (81, N'F81', N'Desaturación T2(L)', N'F81 Desaturación T2(L)', N'Crítico', N'No'),
    (82, N'F82', N'Desaturación T3(L)', N'F82 Desaturación T3(L)', N'Crítico', N'No'),
    (83, N'F83', N'Desaturaciones', N'F83 Desaturaciones', N'Crítico', N'No'),
    (84, N'F84', N'Comunicaciones', N'F84 Comunicaciones', N'Crítico', N'No'),
    (85, N'F85', N'Timeout carga suave', N'F85 Timeout carga suave', N'Crítico', N'No'),
    (86, N'F86', N'Retroaviso seccionador', N'F86 Retroaviso seccionador', N'Crítico', N'No'),
    (90, N'F90', N'Temperatura IGBT HF', N'F90 Temperatura IGBT HF', N'Crítico', N'No'),
    (95, N'F95', N'Fuente PCB', N'F95 Fuente PCB', N'Crítico', N'No'),
    (98, N'F98', N'Derivación Id', N'F98 Derivación Id', N'Crítico', N'No'),
    (99, N'F99', N'Mod. Derivación Iac', N'F99 Mod. Derivación Iac', N'Crítico', N'No'),
    (101, N'F101', N'MOD. MEDIDA DC', N'F101 MOD. MEDIDA DC', NULL, N'No'),
    (102, N'F102', N'Corriente desbalanceada', N'F102 Corriente desbalanceada', N'Crítico', N'No'),
    (103, N'F103', N'Temperatura IGBT', N'F103 Temperatura IGBT', N'Crítico', N'No'),
    (104, N'F104', N'Temperatura PCB', N'F104 Temperatura PCB', N'Crítico', N'No'),
    (106, N'F106', N'Mod. desbalanceo VDC', N'F106 Mod. desbalanceo VDC', N'Crítico', N'No'),
    (107, N'F107', N'Iac no alcanzada', N'F107 Iac no alcanzada', N'Parcial', N'No'),
    (108, N'F108', N'Mod. alta VDC', N'F108 Mod. alta VDC', N'Crítico', N'No'),
    (109, N'F109', N'Mod. baja VDC', N'F109 Mod. baja VDC', N'Crítico', N'No'),
    (112, N'F112', N'Emergencia OCAC', N'F112 Emergencia OCAC', N'Crítico', N'No'),
    (113, N'F113', N'CRC', N'F113 CRC', N'Crítico', N'No'),
    (114, N'F114', N'Sensado Ir', N'F114 Sensado Ir', N'Crítico', N'No'),
    (115, N'F115', N'Sensado Is', N'F115 Sensado Is', N'Crítico', N'No'),
    (116, N'F116', N'Sensado It', N'F116 Sensado It', N'Crítico', N'No'),
    (118, N'F118', N'Módulo deshabilitado', N'F118 Módulo deshabilitado', N'Parcial', N'No'),
    (119, N'F119', N'Desaturación R1(L)', N'F119 Desaturación R1(L)', N'Crítico', N'No'),
    (120, N'F120', N'Desaturación R3(H)', N'F120 Desaturación R3(H)', N'Crítico', N'No'),
    (121, N'F121', N'Desaturación S1(L)', N'F121 Desaturación S1(L)', N'Crítico', N'No'),
    (122, N'F122', N'Desaturación S3(H)', N'F122 Desaturación S3(H)', N'Crítico', N'No'),
    (123, N'F123', N'Desaturación T1(L)', N'F123 Desaturación T1(L)', N'Crítico', N'No'),
    (124, N'F124', N'Desaturación T3(H)', N'F124 Desaturación T3(H)', N'Crítico', N'No'),
    (125, N'F125', N'Dif Iac mod marcha', N'F125 Dif Iac mod marcha', N'Crítico', N'No'),
    (128, N'F128', N'Muelle cargado', N'F128 Muelle cargado', N'No disponible', N'No'),
    (129, N'F129', N'Aislamiento módulo', N'F129 Aislamiento módulo', N'Crítico', N'No'),
    (130, N'F130', N'Carga suave feedback', N'F130 Carga suave feedback', N'Crítico', N'No'),
    (131, N'F131', N'Límite fallos superado', N'F131 Límite fallos superado', N'Crítico', N'No'),
    (132, N'F132', N'Sobretensión HW VDC', N'F132 Sobretensión HW VDC', N'Crítico', N'No'),
    (134, N'F134', N'Sensor módulo comms', N'F134 Sensor módulo comms', N'Crítico', N'No'),
    (139, N'F139', N'VDC mod. baja recup', N'F139 VDC mod. baja recup', N'Crítico', N'No'),
    (150, N'F150', N'Celda MV estado erróneo', N'F150 Celda MV estado erróneo', N'Crítico', N'No'),
    (152, N'F152', N'DGPT2 fallo temperatura', N'F152 DGPT2 fallo temperatura', N'Crítico', N'No'),
    (153, N'F153', N'DGPT2 fallo presión', N'F153 DGPT2 fallo presión', N'Crítico', N'No'),
    (155, N'F155', N'DGPT2 nivel aceite o gas', N'F155 DGPT2 nivel aceite o gas', N'Crítico', N'No'),
    (157, N'F157', N'Retro. seccionador AC', N'F157 Retro. seccionador AC', N'Crítico', N'No'),
    (158, N'F158', N'Baja presión SF6', N'F158 Baja presión SF6', N'Crítico', N'No'),
    (159, N'F159', N'Sobretemperatura DU', N'F159 Sobretemperatura DU', N'Crítico', N'No'),
    (161, N'F161', N'LOTO AC', N'F161 LOTO AC', N'No disponible', N'No'),
    (162, N'F162', N'LOTO DC', N'F162 LOTO DC', N'No disponible', N'No'),
    (163, N'F163', N'WD Celda MV', N'F163 WD Celda MV', N'Crítico', N'No'),
    (164, N'F164', N'Exceso maniobras', N'F164 Exceso maniobras', N'Crítico', N'No'),
    (165, N'F165', N'Modulación indebida', N'F165 Modulación indebida', N'Crítico', N'No'),
    (166, N'F166', N'E-STOP', N'F166 E-STOP', N'Crítico', N'No'),
    (167, N'F167', N'DU abierta', N'F167 DU abierta', N'No disponible', N'No'),
    (169, N'F169', N'Retroaviso LCL', N'F169 Retroaviso LCL', N'Crítico', N'No'),
    (170, N'F170', N'Retroaviso térmico L', N'F170 Retroaviso térmico L', N'Crítico', N'No'),
    (171, N'F171', N'Corriente filtro LC desbal', N'F171 Corriente filtro LC desbal', N'Crítico', N'No'),
    (172, N'F172', N'C filtro LC', N'F172 C filtro LC', N'Crítico', N'No'),
    (173, N'F173', N'Medida CTs', N'F173 Medida CTs', N'Crítico', N'No'),
    (174, N'F174', N'Retro. disyuntor CA', N'F174 Retro. disyuntor CA', N'Crítico', N'No'),
    (175, N'F175', N'Sobrecorriente C', N'F175 Sobrecorriente C', N'Crítico', N'No'),
    (176, N'F176', N'Multi. Event Sobrecorr', N'F176 Multi. Event Sobrecorr', N'Crítico', N'No'),
    (177, N'F177', N'Config. Flt C Error', N'F177 Config. Flt C Error', N'Crítico', N'No'),
    (190, N'F190', N'Combinada F-V', N'F190 Combinada F-V', N'Crítico', N'No'),
    (197, N'F197', N'Sobretensión HW', N'F197 Sobretensión HW', N'Crítico', N'No'),
    (198, N'F198', N'Subtensión HW', N'F198 Subtensión HW', N'Crítico', N'No'),
    (200, N'F200', N'Sobretensión LIn DC', N'F200 Sobretensión LIn DC', N'Crítico', N'No'),
    (202, N'F202', N'Sobretemperatura TAux', N'F202 Sobretemperatura TAux', N'Crítico', N'No'),
    (203, N'F203', N'Sobretemperatura MV', N'F203 Sobretemperatura MV', N'Crítico', N'No'),
    (204, N'F204', N'Vent. impulsión MT', N'F204 Vent. impulsión MT', N'Crítico', N'No'),
    (205, N'F205', N'Vent. zona DU', N'F205 Vent. zona DU', N'Crítico', N'No'),
    (206, N'F206', N'Vent. zona filtro LC', N'F206 Vent. zona filtro LC', N'Crítico', N'No'),
    (207, N'F207', N'Vent. zona módulos', N'F207 Vent. zona módulos', N'Crítico', N'No'),
    (208, N'F208', N'CRI SOBRETEMPERATURA MV', N'F208 CRI SOBRETEMPERATURA MV', NULL, N'No'),
    (210, N'F210', N'COMUNICACIONES UC-FPGA', N'F210 COMUNICACIONES UC-FPGA', NULL, N'No'),
    (211, N'F211', N'AISLAMIENTO INTERNO', N'F211 AISLAMIENTO INTERNO', NULL, N'No'),
    (212, N'F212', N'AISLAMIENTO EXTERNO', N'F212 AISLAMIENTO EXTERNO', NULL, N'No'),
    (213, N'F213', N'DU corriente negativa', N'F213 DU corriente negativa', N'Crítico', N'No'),
    (214, N'F214', N'IMD Comms', N'F214 IMD Comms', N'Crítico', NULL),
    (215, N'F215', N'Timeout GFDI', N'F215 Timeout GFDI', N'Crítico', NULL),
    (216, N'F216', N'Timeout IMI Medida', N'F216 Timeout IMI Medida', N'Crítico', NULL),
    (217, N'F217', N'Temp crítica filtro LC', N'F217 Temp crítica filtro LC', N'Crítico', NULL),
    (219, N'F219', N'Sobretensión Lim AC', N'F219 Sobretensión Lim AC', N'Crítico', NULL),
    (220, N'F220', N'PT100 induc no conectada', N'F220 PT100 induc no conectada', N'Parcial', NULL),
    (221, N'F221', N'PT100 trafo no conectada', N'F221 PT100 trafo no conectada', N'Parcial', NULL),
    (222, N'F222', N'NTC temp adm no conect', N'F222 NTC temp adm no conect', N'Parcial', NULL),
    (223, N'F223', N'NTC filtro LC no conect', N'F223 NTC filtro LC no conect', N'Parcial', NULL),
    (224, N'F224', N'Sobretemperatura Ind', N'F224 Sobretemperatura Ind', N'Crítico', NULL),
    (225, N'F225', N'Cr sobretemperatura Ind', N'F225 Cr sobretemperatura Ind', N'Crítico', NULL),
    (226, N'F226', N'IMI Hardware', N'F226 IMI Hardware', N'Crítico', NULL),
    (227, N'F227', N'Fallo desconocido', N'F227 Fallo desconocido', N'Crítico', NULL),
    (228, N'F228', N'Consigna ventilador', N'F228 Consigna ventilador', N'Crítico', NULL),
    (229, N'F229', N'Timeout canal IMI', N'F229 Timeout canal IMI', N'Crítico', NULL),
    (230, N'F230', N'Tipo vent. incorrect DU', N'F230 Tipo vent. incorrect DU', N'Crítico', NULL),
    (231, N'F231', N'Tipo vent. incorrect MT', N'F231 Tipo vent. incorrect MT', N'Crítico', NULL),
    (232, N'F232', N'Tipo vent. incorrect MOD', N'F232 Tipo vent. incorrect MOD', N'Crítico', NULL),
    (234, N'F234', N'Térmico Bus Plus', N'F234 Térmico Bus Plus', N'Crítico', NULL),
    (235, N'F235', N'T/H sensores comms', N'F235 T/H sensores comms', N'Parcial', NULL),
    (236, N'F236', N'Sensor DU pérdida Coms', N'F236 Sensor DU pérdida Coms', N'Parcial', NULL),
    (237, N'F237', N'Fusible unión negativo', N'F237 Fusible unión negativo', N'Crítico', NULL),
    (238, N'F238', N'AEMO pérdida comms', N'F238 AEMO pérdida comms', N'Comunicación', NULL),
    (240, N'F240', N'DU BP sobrecorriente', N'F240 DU BP sobrecorriente', N'Crítico', NULL),
    (241, N'F241', N'Delta T max DU', N'F241 Delta T max DU', N'Parcial', NULL),
    (242, N'F242', N'Delta T LC', N'F242 Delta T LC', N'Parcial', NULL),
    (243, N'F243', N'Consigna saturada ventilación', N'F243 Consigna saturada ventilación', N'Parcial', NULL),
    (244, N'F244', N'T LC modo silencioso', N'F244 T LC modo silencioso', N'Parcial', NULL),
    (245, N'F245', N'Sobre temp M silencioso', N'F245 Sobre temp M silencioso', N'Parcial', NULL),
    (252, N'F252', N'Sobrecorr RFI persistente', N'F252 Sobrecorr RFI persistente', N'Crítico', NULL),
    (253, N'F253', N'Desbalanceo V', N'F253 Desbalanceo V', N'Crítico', NULL),
    (255, N'F255', N'Detección BAT abierta', N'F255 Detección BAT abierta', N'Crítico', NULL),
    (257, N'F257', N'Timeout carga suave AC', N'F257 Timeout carga suave AC', N'Crítico', NULL)
) AS s (IdTipoDetencion, CodigoFalla, DescripcionFallaPE, CodigoDescripcion, Significado, Operativo)
ON t.IdTipoDetencion = s.IdTipoDetencion
WHEN MATCHED THEN UPDATE SET
    CodigoFalla = s.CodigoFalla, DescripcionFallaPE = s.DescripcionFallaPE, CodigoDescripcion = s.CodigoDescripcion,
    Significado = s.Significado, Operativo = s.Operativo
WHEN NOT MATCHED THEN
    INSERT (IdTipoDetencion, CodigoFalla, DescripcionFallaPE, CodigoDescripcion, Significado, Operativo)
    VALUES (s.IdTipoDetencion, s.CodigoFalla, s.DescripcionFallaPE, s.CodigoDescripcion, s.Significado, s.Operativo);
GO
